---
title: "Texture triangles"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{texture_triangle}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
library(soilR)
library(tidyverse)
library(ggtern)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  dpi = 600,
  fig.width = 7,
  fig.height = 4,
  fig.align = "center",
  out.width = "100%"
)
```

```{r texture-triangle-usda}
ggplot(data = soil_texture_triangle_usda,
       aes(y = clay,
           x = sand,
           z = silt,
           fill = texture)) +
  coord_tern("x",
             "y",
             "z") +
  theme_rgbw() +
  theme_showsecondary() +
  theme_showarrows() +
  custom_percent("(%)") +
  theme(legend.justification = c(0, 1),
        legend.position      = c(0, 1)) +
  labs(title = "USDA texture triangle",
       fill  = 'Texture',
       color = 'Texture') +
  geom_polygon(color = "black") +
  geom_point(data = soil_texture_triangle_usda %>%
               group_by(texture) %>%
               summarise(mZ = mean(silt),
                         mY = mean(clay)),
             aes(x = 100 - mY - mZ,
                 y = mY, z = mZ),
             size = 3)
```

```{r Y_triangles-de-texture_AISNE}
ggplot(data = soil_texture_triangle_aisne,
       aes(y = clay,
           x = sand,
           z = silt,
           fill = texture)) +
  coord_tern("x",
             "y",
             "z") +
  theme_rgbw() +
  theme_showsecondary() +
  theme_showarrows() +
  custom_percent("(%)") +
  theme(legend.justification = c(0, 1),
        legend.position      = c(0, 1)) +
  labs(title = "Aisne texture triangle",
       fill  = 'Texture',
       color = 'Texture') +
  geom_polygon(color = "black") +
  geom_point(data = soil_texture_triangle_aisne %>%
               group_by(texture) %>%
               summarise(mZ = mean(silt),
                         mY = mean(clay)),
             aes(x = 100 - mY - mZ,
                 y = mY, z = mZ),
             size = 3)
```
